# Generated by Django 5.1.6 on 2025-03-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_email_verified',
        ),
    ]
