# Generated by Django 5.1.6 on 2025-02-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassSpellList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'class_spell_lists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('spell_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('spell_level', models.IntegerField()),
                ('spell_school', models.CharField(max_length=100)),
                ('spell_casting_time', models.CharField(max_length=100)),
                ('spell_reaction', models.TextField(blank=True, null=True)),
                ('spell_ritual', models.BooleanField(default=False)),
                ('spell_range', models.CharField(blank=True, max_length=100, null=True)),
                ('spell_components', models.CharField(blank=True, max_length=255, null=True)),
                ('spell_materials', models.TextField(blank=True, null=True)),
                ('spell_duration', models.CharField(max_length=100)),
                ('spell_concentration', models.BooleanField(default=False)),
                ('spell_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'spells',
                'managed': False,
            },
        ),
    ]
