# Generated by Django 5.1.6 on 2025-02-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdventuringFeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat_name', models.CharField(max_length=255, unique=True)),
                ('feat_description', models.TextField()),
            ],
            options={
                'db_table': 'adventuring_feats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdventuringFeatPrereq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'adventuring_feat_prereqs',
                'managed': False,
            },
        ),
    ]
